version: '3.8'
services:
  app_prod:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    container_name: laravel_prod
    ports:
      - "9003:80"
    restart: always

  app_stage:
    build:
      context: .
      dockerfile: dockerfiles/stage.Dockerfile
    container_name: laravel_stage
    ports:
      - "9004:80"
    restart: always

  app_dev:
    build:
      context: .
      dockerfile: dockerfiles/stage.Dockerfile
    container_name: laravel_dev
    restart: no
    ports:
      - "8000:8000"
    entrypoint: [ "sh", "-c", "php artisan migrate && php artisan serve --host=0.0.0.0" ]
    depends_on:
      - db_dev

  db_dev:
    image: postgres:latest
    container_name: postgres_dev
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: laravel_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: